"""Updated Payment table with status, auth_code and time fields

Revision ID: d0c201988e23
Revises: ad9528b5289d
Create Date: 2022-04-23 15:50:33.950769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0c201988e23'
down_revision = 'ad9528b5289d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('status', sa.String(length=32), nullable=True))
    op.add_column('payment', sa.Column('authorization_code', sa.String(length=32), nullable=True))
    op.add_column('payment', sa.Column('time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'time')
    op.drop_column('payment', 'authorization_code')
    op.drop_column('payment', 'status')
    # ### end Alembic commands ###
